version: '3.8'

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/db
  redisDB:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/redis

services:

  frontend:
    image: node:18-alpine
    container_name: frontend
    build: ./front
    networks:
      - dream
    ports:
      - '3000:3000'
    volumes:
      - ./front/src:/app


  backend:
    image: node:18-alpine
    container_name: backend
    build: ./backend
    networks:
      - dream
    ports:
      - '4242:4242'
    volumes:
      - ./backend/src/backend:/app
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: wrtn

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    tty: true
    networks:
      - dream
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgressql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: wrtn

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: on-failure:5
    ports:
      - '5050:80'
    tty: true
    networks:
      - dream
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=1234

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - '6379:6379'
    tty: true
    networks:
      - dream
    volumes:
      - redisDB:/data
    command: /bin/sh -c "redis-server --requirepass $$REDIS_HOST_PASSWORD"
    environment:
      - REDIS_HOST=redis
      - REDIS_TLS=true
      - REDIS_HOST_PASSWORD=1234


networks:
  dream:
    name: dream
    driver: bridge
